name: trending_repository_middleware
description: A repository that handles todo related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  rxdart: ^0.27.2
  shared_preferences: ^2.0.7
  trending_common:
    path: ../trending_common

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.17.0
  very_good_analysis: ^3.0.1
