name: local_storage_repository_middleware
description: A Flutter implementation of the TodosApi that uses local storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  flutter:
    sdk: flutter
  repository_middleware:
    path: ../repository_middleware
  trending_common:
    path: ../trending_common
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
